const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const projectRoot=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(projectRoot,'index.html'),'utf8');
const updatesScript=fs.readFileSync(path.join(projectRoot,'assets/js/updates.js'),'utf8');
const script=fs.readFileSync(path.join(projectRoot,'assets/js/checklist.js'),'utf8');
const css=fs.readFileSync(path.join(projectRoot,'assets/css/shared.css'),'utf8')+fs.readFileSync(path.join(projectRoot,'assets/css/checklist.css'),'utf8');
new vm.Script(updatesScript);
new vm.Script(script);
const checkboxHandlerSource=script.slice(script.indexOf("addEventListener('change'"),script.indexOf("addEventListener('input'"));
assert(checkboxHandlerSource.includes('refreshProgressUI();'),'Checkboxes must use the non-destructive progress updater');
assert(!checkboxHandlerSource.includes('paint();'),'Checkboxes must not rebuild the page or reload the embedded map');
function app(storage={}){
  const handlers={}, windowHandlers={};
  const classes=new Set();
  const noop=()=>{};
  const element=()=>({style:{},setAttribute:noop,removeAttribute:noop,appendChild:noop,addEventListener:noop,classList:{toggle:noop,add:noop,remove:noop},querySelectorAll:()=>[]});
  const root=element();root.innerHTML='';root.addEventListener=(key,fn)=>handlers[key]=fn;root.classList.toggle=(name,on)=>on?classes.add(name):classes.delete(name);
  const document={documentElement:element(),head:element(),body:element(),createElement:element,querySelector:()=>null,querySelectorAll:()=>[],getElementById:id=>id==='root'?root:null,addEventListener:noop};
  const window={innerWidth:1280,matchMedia:()=>({matches:false,addEventListener:noop,addListener:noop}),addEventListener:(key,fn)=>windowHandlers[key]=fn};
  const localStorage={getItem:key=>storage[key]??null,setItem:(key,val)=>storage[key]=val,removeItem:key=>delete storage[key]};
  const ctx={document,window,localStorage,setTimeout:()=>1,clearTimeout:noop,requestAnimationFrame:noop,console};
  vm.runInNewContext(updatesScript,ctx);
  vm.runInNewContext(script,ctx);
  return {root,handlers,windowHandlers,storage,classes};
}
const fresh=app();
assert.equal((fresh.root.innerHTML.match(/<section class="cat /g)||[]).length,7);
assert(fresh.root.innerHTML.includes('RDR2 清单'));
const updatesContext={window:{}};
vm.runInNewContext(updatesScript,updatesContext);
assert(fresh.root.innerHTML.includes(updatesContext.window.RDR2Updates.latestText('zh')),'Latest update announcement missing from checklist');
assert(fresh.root.innerHTML.includes('找到并与5名特殊路人互动'));
assert(fresh.root.innerHTML.includes('0 / 39'));
assert(fresh.root.innerHTML.includes('营地请求&amp;活动'));
assert(fresh.root.innerHTML.includes('找遍天涯海角'));
assert(fresh.root.innerHTML.includes('真爱易逝（I–III）'));
assert(fresh.root.innerHTML.includes('曾经的梦想（I–II）'));
assert(fresh.root.innerHTML.includes('和蓝尼玩快刀戳指缝'));
assert(fresh.root.innerHTML.includes('和迈卡抢劫马车'));
assert.equal((fresh.root.innerHTML.match(/<nav /g)||[]).length,(fresh.root.innerHTML.match(/<\/nav>/g)||[]).length);
const ids=[...fresh.root.innerHTML.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
// Attribute boundaries avoid counting data-id as HTML id.
const htmlIds=[...fresh.root.innerHTML.matchAll(/(?:\s|<)id="([^"]+)"/g)].map(x=>x[1]);
assert.equal(new Set(htmlIds).size,htmlIds.length,'Duplicate element IDs');
const note='A note <with> "special" characters';
const edited=app({'rdr2-full-checklist-v2':JSON.stringify({a1:{c:true,m:note},la3:{c:false,m:''}})});
assert(edited.root.innerHTML.includes('cb-a1" data-id="a1" checked'),'Saved checkbox must override embedded state');
assert(!edited.root.innerHTML.includes('cb-la3" data-id="la3" checked'),'Saved uncheck must override embedded check');
assert(edited.root.innerHTML.includes('A note &lt;with&gt; &quot;special&quot; characters'));
edited.handlers.change({target:{closest:()=>({dataset:{id:'a1'},checked:false})}});
edited.windowHandlers.pagehide();
assert.equal(JSON.parse(edited.storage['rdr2-full-checklist-v2']).a1.c,false);
assert.equal(JSON.parse(edited.storage['rdr2-full-checklist-v2']).a1.m,note);
edited.handlers.input({target:{id:'search',value:'圣丹尼斯'}});
assert(edited.classes.has('is-searching'));
edited.handlers.input({target:{id:'search',value:''}});
assert(!edited.classes.has('is-searching'));
const english=app({'rdr2-full-checklist-lang':'en'});
assert(english.root.innerHTML.includes('RDR2 Todo list'));
assert(english.root.innerHTML.includes(updatesContext.window.RDR2Updates.latestText('en')),'Latest English update announcement missing from checklist');
assert(english.root.innerHTML.includes('Search tasks, places or items'));
assert(english.root.innerHTML.includes('Find and interact with 5 special characters'));
assert(english.root.innerHTML.includes('>25 chance encounters</label>'));
assert(english.root.innerHTML.includes('Camp Requests &amp; Activities'));
assert(english.root.innerHTML.includes('To the Ends of the Earth'));
assert(english.root.innerHTML.includes('Fatherhood and Other Dreams (I–II)'));
assert(english.root.innerHTML.includes('Five Finger Fillet with Lenny'));
assert(english.root.innerHTML.includes('Complete Friends in Very Low Places in Chapter 3'));
assert(fresh.root.innerHTML.includes('解锁：完成“强盗”挑战第1级'));
assert(fresh.root.innerHTML.includes('解锁：完成“武器专家”挑战第7级'));
assert(english.root.innerHTML.includes('Unlock: complete Bandit Challenge 1'));
assert(english.root.innerHTML.includes('Unlock: complete Weapons Expert Challenge 7'));
assert(!fresh.root.innerHTML.includes('class="row-en"'));
const visible=markup=>markup.replace(/<[^>]*>/g,' ');
assert(!visible(english.root.innerHTML).includes('，'),'English mode must not render Chinese commas');
assert(!visible(english.root.innerHTML).includes('；'),'English mode must not render Chinese semicolons');
assert(visible(english.root.innerHTML).includes('Chapter 4 - Complete We Loved Once and True'));
assert(!visible(fresh.root.innerHTML).includes('范葛伦'));
assert(!visible(fresh.root.innerHTML).includes('Jeremiah Compson'));
assert(visible(fresh.root.innerHTML).includes('耶利米·康普森'));
assert(visible(english.root.innerHTML).includes('Jeremiah Compson'));
const explorationNote='我的旧备注 English personal note';
const migrated=app({'rdr2-full-checklist-v2':JSON.stringify({d2:{c:true,m:'原枪手总项'},d15:{c:true,m:explorationNote}})});
assert(migrated.root.innerHTML.includes('cb-d2" data-id="d2" checked'));
assert(migrated.root.innerHTML.includes('cb-d15" data-id="d15" checked'));
assert(migrated.root.innerHTML.includes(explorationNote));
assert(!migrated.root.innerHTML.includes('cb-w_flaco" data-id="w_flaco" checked'));
assert(!migrated.root.innerHTML.includes('cb-w_calloway" data-id="w_calloway" checked'));
migrated.handlers.change({target:{closest:()=>({dataset:{id:'w_flaco'},checked:true})}});
migrated.windowHandlers.pagehide();
const migratedReload=app(migrated.storage);
assert(migratedReload.root.innerHTML.includes('cb-w_flaco" data-id="w_flaco" checked'));
assert(!migratedReload.root.innerHTML.includes('cb-w_granger" data-id="w_granger" checked'));
assert(migratedReload.root.innerHTML.includes(explorationNote));
const malformed=app({'rdr2-full-checklist-v2':'{bad json'});
assert(malformed.root.innerHTML.includes('RDR2 清单'));

// Trapper garment-set parents must keep their material-only child checklist in sync.
const trapper=app();
trapper.handlers.change({target:{closest:()=>({dataset:{id:'trc1'},checked:true})}});
trapper.windowHandlers.pagehide();
const trapperSaved=JSON.parse(trapper.storage['rdr2-full-checklist-v2']);
assert.equal(trapperSaved.trc1.c,true);
assert.equal(trapperSaved.trc1_1.c,true);
assert.equal(trapperSaved.trc1_4.c,true);
trapper.handlers.change({target:{closest:()=>({dataset:{id:'trc1_2'},checked:false})}});
trapper.windowHandlers.pagehide();
const trapperPartial=JSON.parse(trapper.storage['rdr2-full-checklist-v2']);
assert.equal(trapperPartial.trc1.c,false,'A garment set must become incomplete when a child item is unchecked');
assert.equal(trapperPartial.trc1_1.c,true,'Sibling garment state must be preserved');

// Existing trinkets/talismans and new reinforced equipment share Compendium state.
const linked=app();
linked.handlers.change({target:{closest:()=>({dataset:{id:'tk1'},checked:true})}});
linked.handlers.change({target:{closest:()=>({dataset:{id:'re36'},checked:true})}});
const linkedCompendium=JSON.parse(linked.storage['rdr2-compendium-v1']);
assert.equal(linkedCompendium['equipment-23'],true);
assert.equal(linkedCompendium['equipment-79'],true);
const linkedReload=app(linked.storage);
assert(linkedReload.root.innerHTML.includes('cb-tk1" data-id="tk1" checked'));
assert(linkedReload.root.innerHTML.includes('cb-re36" data-id="re36" checked'));

assert(!css.includes('@import url('),'Offline file must not require external fonts');
assert(css.includes('prefers-reduced-motion'));
assert(css.includes('prefers-reduced-transparency'));
console.log('PASS: JavaScript, 7 checklist sections, unique IDs, bilingual rendering, saved progress and notes, Trapper parent/child state, Compendium links, reload recovery, search state and accessibility fallbacks.');
console.log('Validation uses an isolated DOM stub; no browser interaction or visual QA was performed.');
